In [2]:
import requests
import json
import pandas as pd
import numpy as np
import psycopg2
from psycopg2.extras import execute_values

In [3]:
##insert movies##
url='https://api.themoviedb.org/3/movie/top_rated?api_key=76f3ff736cde9a95c8dde41456f28cda&language=en-US&page={}'
    
response = requests.get(url)
if response.status_code==200:
      
            movies = pd.DataFrame(response.json()["results"])[['id','original_title','release_date','genre_ids','vote_average','vote_count']]
            
        
for i in range(1, 4):
             response = requests.get(url)
             temp_df = pd.DataFrame(response.json()["results"])[['id','original_title','release_date','genre_ids','vote_average','vote_count']]
             movies.append(temp_df, ignore_index=False)
        
        
             #print(movies) ##Visualizo los datos
             
## rename it original_title as name

C:\Users\Adriana Prieto\AppData\Local\Temp\ipykernel_47536\256939419.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  movies.append(temp_df, ignore_index=False)

        id                                 original_title release_date  \
0      238                                  The Godfather   1972-03-14
1      278                       The Shawshank Redemption   1994-09-23
2   772071                               Cuando Sea Joven   2022-09-14
3      240                          The Godfather Part II   1974-12-20
4    19404                   दिलवाले दुल्हनिया ले जायेंगे   1995-10-19
5      424                               Schindler's List   1993-12-15
6      129                                       千と千尋の神隠し   2001-07-20
7      389                                   12 Angry Men   1957-04-10
8   372058                                          君の名は。   2016-08-26
9   496243                                            기생충   2019-05-30
10     155                                The Dark Knight   2008-07-14
11     497                                 The Green Mile   1999-12-10
12     680                                   Pulp Fiction   1994-09-10
13     429                Il buono, il brutto, il cattivo   1966-12-23
14      13                                   Forrest Gump   1994-06-23
15  372754                                            同級生   2016-02-20
16     122  The Lord of the Rings: The Return of the King   2003-12-01
17     769                                     GoodFellas   1990-09-12
18  704264                      Primal: Tales of Savagery   2019-11-21
19  995133       The Boy, the Mole, the Fox and the Horse   2022-12-25

              genre_ids  vote_average  vote_count
0              [18, 80]           8.7       17944
1              [18, 80]           8.7       23783
2              [35, 14]           8.6         226
3              [18, 80]           8.6       10831
4       [35, 18, 10749]           8.6        4131
5       [18, 36, 10752]           8.6       14068
6       [16, 10751, 14]           8.5       14302
7                  [18]           8.5        7273
8       [10749, 16, 18]           8.5        9840
9          [35, 53, 18]           8.5       15734
10     [18, 28, 80, 53]           8.5       29719
11         [14, 18, 80]           8.5       15406
12             [53, 80]           8.5       25179
13                 [37]           8.5        7396
14      [35, 18, 10749]           8.5       24664
15          [10749, 16]           8.5         304
16         [12, 14, 28]           8.5       21594
17             [18, 80]           8.5       11256
18     [28, 12, 16, 18]           8.5         263
19  [16, 10751, 12, 14]           8.5         323

C:\Users\Adriana Prieto\AppData\Local\Temp\ipykernel_47536\256939419.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  movies.append(temp_df, ignore_index=False)

        id                                 original_title release_date  \
0      238                                  The Godfather   1972-03-14
1      278                       The Shawshank Redemption   1994-09-23
2   772071                               Cuando Sea Joven   2022-09-14
3      240                          The Godfather Part II   1974-12-20
4    19404                   दिलवाले दुल्हनिया ले जायेंगे   1995-10-19
5      424                               Schindler's List   1993-12-15
6      129                                       千と千尋の神隠し   2001-07-20
7      389                                   12 Angry Men   1957-04-10
8   372058                                          君の名は。   2016-08-26
9   496243                                            기생충   2019-05-30
10     155                                The Dark Knight   2008-07-14
11     497                                 The Green Mile   1999-12-10
12     680                                   Pulp Fiction   1994-09-10
13     429                Il buono, il brutto, il cattivo   1966-12-23
14      13                                   Forrest Gump   1994-06-23
15  372754                                            同級生   2016-02-20
16     122  The Lord of the Rings: The Return of the King   2003-12-01
17     769                                     GoodFellas   1990-09-12
18  704264                      Primal: Tales of Savagery   2019-11-21
19  995133       The Boy, the Mole, the Fox and the Horse   2022-12-25

              genre_ids  vote_average  vote_count
0              [18, 80]           8.7       17944
1              [18, 80]           8.7       23783
2              [35, 14]           8.6         226
3              [18, 80]           8.6       10831
4       [35, 18, 10749]           8.6        4131
5       [18, 36, 10752]           8.6       14068
6       [16, 10751, 14]           8.5       14302
7                  [18]           8.5        7273
8       [10749, 16, 18]           8.5        9840
9          [35, 53, 18]           8.5       15734
10     [18, 28, 80, 53]           8.5       29719
11         [14, 18, 80]           8.5       15406
12             [53, 80]           8.5       25179
13                 [37]           8.5        7396
14      [35, 18, 10749]           8.5       24664
15          [10749, 16]           8.5         304
16         [12, 14, 28]           8.5       21594
17             [18, 80]           8.5       11256
18     [28, 12, 16, 18]           8.5         263
19  [16, 10751, 12, 14]           8.5         323
        id                                 original_title release_date  \
0      238                                  The Godfather   1972-03-14
1      278                       The Shawshank Redemption   1994-09-23
2   772071                               Cuando Sea Joven   2022-09-14
3      240                          The Godfather Part II   1974-12-20
4    19404                   दिलवाले दुल्हनिया ले जायेंगे   1995-10-19
5      424                               Schindler's List   1993-12-15
6      129                                       千と千尋の神隠し   2001-07-20
7      389                                   12 Angry Men   1957-04-10
8   372058                                          君の名は。   2016-08-26
9   496243                                            기생충   2019-05-30
10     155                                The Dark Knight   2008-07-14
11     497                                 The Green Mile   1999-12-10
12     680                                   Pulp Fiction   1994-09-10
13     429                Il buono, il brutto, il cattivo   1966-12-23
14      13                                   Forrest Gump   1994-06-23
15  372754                                            同級生   2016-02-20
16     122  The Lord of the Rings: The Return of the King   2003-12-01
17     769                                     GoodFellas   1990-09-12
18  704264                      Primal: Tales of Savagery   2019-11-21
19  995133       The Boy, the Mole, the Fox and the Horse   2022-12-25

              genre_ids  vote_average  vote_count
0              [18, 80]           8.7       17944
1              [18, 80]           8.7       23783
2              [35, 14]           8.6         226
3              [18, 80]           8.6       10831
4       [35, 18, 10749]           8.6        4131
5       [18, 36, 10752]           8.6       14068
6       [16, 10751, 14]           8.5       14302
7                  [18]           8.5        7273
8       [10749, 16, 18]           8.5        9840
9          [35, 53, 18]           8.5       15734
10     [18, 28, 80, 53]           8.5       29719
11         [14, 18, 80]           8.5       15406
12             [53, 80]           8.5       25179
13                 [37]           8.5        7396
14      [35, 18, 10749]           8.5       24664
15          [10749, 16]           8.5         304
16         [12, 14, 28]           8.5       21594
17             [18, 80]           8.5       11256
18     [28, 12, 16, 18]           8.5         263
19  [16, 10751, 12, 14]           8.5         323

C:\Users\Adriana Prieto\AppData\Local\Temp\ipykernel_47536\256939419.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  movies.append(temp_df, ignore_index=False)

In [4]:
#convierto el index como columna del df movies
movies['index'] = movies.index

In [5]:
##convierto el campo genre_ids a lista y completo el largo de la sublista##
genre_ids=movies['genre_ids'].tolist()

tamanio=len (genre_ids)
for i in range(tamanio):
    longitud = len(genre_ids[i])
   # print(longitud)
    while longitud<5:
        genre_ids[i].append(0)
       # print(genre_ids[i])
        longitud+=1
    #print(longitud)

#print(genre_ids)

In [7]:
#convierto la lista genre_ids a dataframe##
df_genre_ids = pd.DataFrame(genre_ids)
#convierto el index como columna
df_genre_ids['index'] = df_genre_ids.index
print(df_genre_ids)

        0      1      2   3  4  index
0      18     80      0   0  0      0
1      18     80      0   0  0      1
2      35     14      0   0  0      2
3      18     80      0   0  0      3
4      35     18  10749   0  0      4
5      18     36  10752   0  0      5
6      16  10751     14   0  0      6
7      18      0      0   0  0      7
8   10749     16     18   0  0      8
9      35     53     18   0  0      9
10     18     28     80  53  0     10
11     14     18     80   0  0     11
12     53     80      0   0  0     12
13     37      0      0   0  0     13
14     35     18  10749   0  0     14
15  10749     16      0   0  0     15
16     12     14     28   0  0     16
17     18     80      0   0  0     17
18     28     12     16  18  0     18
19     16  10751     12  14  0     19

In [8]:
#Uno df movies con df idf_genre_ids por el index
peliculas=pd.merge(movies,df_genre_ids,on='index',how='left')
#peliculas

In [9]:
## renombro columnas en df peliculas##
peliculas.rename(columns = {'original_title':'nombre','release_date':'fecha_lanzamiento','genre_ids':'id_genero','vote_average':'voto_prom','vote_count':'voto_cant',0:'G0',1:'G1',2:'G2',3:'G3',4:'G4'}, inplace = True)

#creo y completo la columna tipo_streaming
peliculas["tipo_streaming"] = np.nan
peliculas["tipo_streaming"].fillna("peliculas", inplace = True)
#peliculas

,id,nombre,fecha_lanzamiento,id_genero,voto_prom,voto_cant,index,G0,G1,G2,G3,G4,tipo_streaming
0,238,The Godfather,1972-03-14,"[18, 80, 0, 0, 0]",8.7,17944,0,18,80,0,0,0,peliculas
1,278,The Shawshank Redemption,1994-09-23,"[18, 80, 0, 0, 0]",8.7,23783,1,18,80,0,0,0,peliculas
2,772071,Cuando Sea Joven,2022-09-14,"[35, 14, 0, 0, 0]",8.6,226,2,35,14,0,0,0,peliculas
3,240,The Godfather Part II,1974-12-20,"[18, 80, 0, 0, 0]",8.6,10831,3,18,80,0,0,0,peliculas
4,19404,दिलवाले दुल्हनिया ले जायेंगे,1995-10-19,"[35, 18, 10749, 0, 0]",8.6,4131,4,35,18,10749,0,0,peliculas
5,424,Schindler's List,1993-12-15,"[18, 36, 10752, 0, 0]",8.6,14068,5,18,36,10752,0,0,peliculas
6,129,千と千尋の神隠し,2001-07-20,"[16, 10751, 14, 0, 0]",8.5,14302,6,16,10751,14,0,0,peliculas
7,389,12 Angry Men,1957-04-10,"[18, 0, 0, 0, 0]",8.5,7273,7,18,0,0,0,0,peliculas
8,372058,君の名は。,2016-08-26,"[10749, 16, 18, 0, 0]",8.5,9840,8,10749,16,18,0,0,peliculas
9,496243,기생충,2019-05-30,"[35, 53, 18, 0, 0]",8.5,15734,9,35,53,18,0,0,peliculas
10,155,The Dark Knight,2008-07-14,"[18, 28, 80, 53, 0]",8.5,29719,10,18,28,80,53,0,peliculas
11,497,The Green Mile,1999-12-10,"[14, 18, 80, 0, 0]",8.5,15406,11,14,18,80,0,0,peliculas
12,680,Pulp Fiction,1994-09-10,"[53, 80, 0, 0, 0]",8.5,25179,12,53,80,0,0,0,peliculas
13,429,"Il buono, il brutto, il cattivo",1966-12-23,"[37, 0, 0, 0, 0]",8.5,7396,13,37,0,0,0,0,peliculas
14,13,Forrest Gump,1994-06-23,"[35, 18, 10749, 0, 0]",8.5,24664,14,35,18,10749,0,0,peliculas
15,372754,同級生,2016-02-20,"[10749, 16, 0, 0, 0]",8.5,304,15,10749,16,0,0,0,peliculas
16,122,The Lord of the Rings: The Return of the King,2003-12-01,"[12, 14, 28, 0, 0]",8.5,21594,16,12,14,28,0,0,peliculas
17,769,GoodFellas,1990-09-12,"[18, 80, 0, 0, 0]",8.5,11256,17,18,80,0,0,0,peliculas
18,704264,Primal: Tales of Savagery,2019-11-21,"[28, 12, 16, 18, 0]",8.5,263,18,28,12,16,18,0,peliculas
19,995133,"The Boy, the Mole, the Fox and the Horse",2022-12-25,"[16, 10751, 12, 14, 0]",8.5,323,19,16,10751,12,14,0,peliculas

In [ ]:
############################################################################################################################

In [11]:
##insert series##
url='https://api.themoviedb.org/3/tv/top_rated?api_key=76f3ff736cde9a95c8dde41456f28cda&language=en-US&page={}'
    
response = requests.get(url)
if response.status_code==200:
      
            series = pd.DataFrame(response.json()["results"])[['id','name','first_air_date','genre_ids','vote_average','vote_count']]
        
        
for i in range(1, 4):
             response = requests.get(url)
             temp_df = pd.DataFrame(response.json()["results"])[['id','name','first_air_date','genre_ids','vote_average','vote_count']]
             series.append(temp_df, ignore_index=False)
        
        
            # print(series) ##Visualizo los datos

C:\Users\Adriana Prieto\AppData\Local\Temp\ipykernel_47536\4028453502.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  series.append(temp_df, ignore_index=False)

        id                              name first_air_date  \
0     1396                      Breaking Bad     2008-01-20
1    94605                            Arcane     2021-11-06
2   100088                    The Last of Us     2023-01-15
3    60625                    Rick and Morty     2013-12-02
4    37854                         One Piece     1999-10-20
5    31911  Fullmetal Alchemist: Brotherhood     2009-04-05
6    70785                    Anne with an E     2017-03-19
7    85937    Demon Slayer: Kimetsu no Yaiba     2019-04-06
8    67915                            Goblin     2016-12-02
9    65930                  My Hero Academia     2016-04-03
10   95557                        Invincible     2021-03-25
11   92685                     The Owl House     2020-01-10
12     246        Avatar: The Last Airbender     2005-02-21
13   31132                      Regular Show     2010-09-06
14  114410                      Chainsaw Man     2022-10-12
15   83121          Kaguya-sama: Love Is War     2019-01-12
16  135157                  Alchemy of Souls     2022-06-18
17   89456                            Primal     2019-10-08
18   46298                   Hunter x Hunter     2011-10-02
19  213762  Be Eternal: Champions of America     2022-11-03

                     genre_ids  vote_average  vote_count
0                     [18, 80]           8.9       11690
1       [16, 10765, 10759, 18]           8.8        3061
2                         [18]           8.7        3485
3       [16, 35, 10765, 10759]           8.7        8204
4              [10759, 35, 16]           8.7        3733
5           [10759, 16, 10765]           8.7        1630
6                  [18, 10751]           8.7        4254
7           [16, 10759, 10765]           8.7        5199
8              [18, 10765, 35]           8.7        2469
9                  [10759, 16]           8.7        4327
10      [16, 10765, 10759, 18]           8.7        3480
11  [16, 10765, 18, 10759, 35]           8.7        1300
12          [16, 10759, 10765]           8.7        3280
13                    [16, 35]           8.7        1688
14      [16, 10759, 10765, 35]           8.7        1049
15                [16, 35, 18]           8.7         612
16    [18, 10759, 9648, 10765]           8.7         349
17             [10759, 16, 18]           8.7        1182
18             [10759, 16, 18]           8.7        1374
19                        [99]           8.7         111

C:\Users\Adriana Prieto\AppData\Local\Temp\ipykernel_47536\4028453502.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  series.append(temp_df, ignore_index=False)

        id                              name first_air_date  \
0     1396                      Breaking Bad     2008-01-20
1    94605                            Arcane     2021-11-06
2   100088                    The Last of Us     2023-01-15
3    60625                    Rick and Morty     2013-12-02
4    37854                         One Piece     1999-10-20
5    31911  Fullmetal Alchemist: Brotherhood     2009-04-05
6    70785                    Anne with an E     2017-03-19
7    85937    Demon Slayer: Kimetsu no Yaiba     2019-04-06
8    67915                            Goblin     2016-12-02
9    65930                  My Hero Academia     2016-04-03
10   95557                        Invincible     2021-03-25
11   92685                     The Owl House     2020-01-10
12     246        Avatar: The Last Airbender     2005-02-21
13   31132                      Regular Show     2010-09-06
14  114410                      Chainsaw Man     2022-10-12
15   83121          Kaguya-sama: Love Is War     2019-01-12
16  135157                  Alchemy of Souls     2022-06-18
17   89456                            Primal     2019-10-08
18   46298                   Hunter x Hunter     2011-10-02
19  213762  Be Eternal: Champions of America     2022-11-03

                     genre_ids  vote_average  vote_count
0                     [18, 80]           8.9       11690
1       [16, 10765, 10759, 18]           8.8        3061
2                         [18]           8.7        3485
3       [16, 35, 10765, 10759]           8.7        8204
4              [10759, 35, 16]           8.7        3733
5           [10759, 16, 10765]           8.7        1630
6                  [18, 10751]           8.7        4254
7           [16, 10759, 10765]           8.7        5199
8              [18, 10765, 35]           8.7        2469
9                  [10759, 16]           8.7        4327
10      [16, 10765, 10759, 18]           8.7        3480
11  [16, 10765, 18, 10759, 35]           8.7        1300
12          [16, 10759, 10765]           8.7        3280
13                    [16, 35]           8.7        1688
14      [16, 10759, 10765, 35]           8.7        1049
15                [16, 35, 18]           8.7         612
16    [18, 10759, 9648, 10765]           8.7         349
17             [10759, 16, 18]           8.7        1182
18             [10759, 16, 18]           8.7        1374
19                        [99]           8.7         111
        id                              name first_air_date  \
0     1396                      Breaking Bad     2008-01-20
1    94605                            Arcane     2021-11-06
2   100088                    The Last of Us     2023-01-15
3    60625                    Rick and Morty     2013-12-02
4    37854                         One Piece     1999-10-20
5    31911  Fullmetal Alchemist: Brotherhood     2009-04-05
6    70785                    Anne with an E     2017-03-19
7    85937    Demon Slayer: Kimetsu no Yaiba     2019-04-06
8    67915                            Goblin     2016-12-02
9    65930                  My Hero Academia     2016-04-03
10   95557                        Invincible     2021-03-25
11   92685                     The Owl House     2020-01-10
12     246        Avatar: The Last Airbender     2005-02-21
13   31132                      Regular Show     2010-09-06
14  114410                      Chainsaw Man     2022-10-12
15   83121          Kaguya-sama: Love Is War     2019-01-12
16  135157                  Alchemy of Souls     2022-06-18
17   89456                            Primal     2019-10-08
18   46298                   Hunter x Hunter     2011-10-02
19  213762  Be Eternal: Champions of America     2022-11-03

                     genre_ids  vote_average  vote_count
0                     [18, 80]           8.9       11690
1       [16, 10765, 10759, 18]           8.8        3061
2                         [18]           8.7        3485
3       [16, 35, 10765, 10759]           8.7        8204
4              [10759, 35, 16]           8.7        3733
5           [10759, 16, 10765]           8.7        1630
6                  [18, 10751]           8.7        4254
7           [16, 10759, 10765]           8.7        5199
8              [18, 10765, 35]           8.7        2469
9                  [10759, 16]           8.7        4327
10      [16, 10765, 10759, 18]           8.7        3480
11  [16, 10765, 18, 10759, 35]           8.7        1300
12          [16, 10759, 10765]           8.7        3280
13                    [16, 35]           8.7        1688
14      [16, 10759, 10765, 35]           8.7        1049
15                [16, 35, 18]           8.7         612
16    [18, 10759, 9648, 10765]           8.7         349
17             [10759, 16, 18]           8.7        1182
18             [10759, 16, 18]           8.7        1374
19                        [99]           8.7         111

C:\Users\Adriana Prieto\AppData\Local\Temp\ipykernel_47536\4028453502.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  series.append(temp_df, ignore_index=False)

In [12]:
##convierto el campo genre_ids a lista y completo el largo de la sublista##
genre_id=series['genre_ids'].tolist()

tamanio=len (genre_id)
for i in range(tamanio):
    longitud = len(genre_id[i])
   # print(longitud)
    while longitud<5:
        genre_id[i].append(0)
       # print(genre_ids[i])
        longitud+=1
    #print(longitud)

#print(genre_id)

In [13]:
#convierto la lista genre_ids a dataframe##
df_genre_id = pd.DataFrame(genre_ids)
#convierto el index como columna
df_genre_id['index'] = df_genre_id.index
#print(df_genre_id)

In [14]:
#convierto el index como columna del df series
series['index'] = series.index

In [15]:
#Uno df series con df df_genre_id por el index
series_tv=pd.merge(series,df_genre_ids,on='index',how='left')
#series_tv

In [16]:
## renombro columnas en df series##
series_tv.rename(columns = {'name':'nombre','first_air_date':'fecha_lanzamiento','genre_ids':'id_genero','vote_average':'voto_prom','vote_count':'voto_cant',0:'G0',1:'G1',2:'G2',3:'G3',4:'G4'}, inplace = True)

#creo y completo la columna tipo_streaming
series_tv["tipo_streaming"] = np.nan
series_tv["tipo_streaming"].fillna("series", inplace = True)
series_tv

,id,nombre,fecha_lanzamiento,id_genero,voto_prom,voto_cant,index,G0,G1,G2,G3,G4,tipo_streaming
0,1396,Breaking Bad,2008-01-20,"[18, 80, 0, 0, 0]",8.9,11690,0,18,80,0,0,0,series
1,94605,Arcane,2021-11-06,"[16, 10765, 10759, 18, 0]",8.8,3061,1,18,80,0,0,0,series
2,100088,The Last of Us,2023-01-15,"[18, 0, 0, 0, 0]",8.7,3485,2,35,14,0,0,0,series
3,60625,Rick and Morty,2013-12-02,"[16, 35, 10765, 10759, 0]",8.7,8204,3,18,80,0,0,0,series
4,37854,One Piece,1999-10-20,"[10759, 35, 16, 0, 0]",8.7,3733,4,35,18,10749,0,0,series
5,31911,Fullmetal Alchemist: Brotherhood,2009-04-05,"[10759, 16, 10765, 0, 0]",8.7,1630,5,18,36,10752,0,0,series
6,70785,Anne with an E,2017-03-19,"[18, 10751, 0, 0, 0]",8.7,4254,6,16,10751,14,0,0,series
7,85937,Demon Slayer: Kimetsu no Yaiba,2019-04-06,"[16, 10759, 10765, 0, 0]",8.7,5199,7,18,0,0,0,0,series
8,67915,Goblin,2016-12-02,"[18, 10765, 35, 0, 0]",8.7,2469,8,10749,16,18,0,0,series
9,65930,My Hero Academia,2016-04-03,"[10759, 16, 0, 0, 0]",8.7,4327,9,35,53,18,0,0,series
10,95557,Invincible,2021-03-25,"[16, 10765, 10759, 18, 0]",8.7,3480,10,18,28,80,53,0,series
11,92685,The Owl House,2020-01-10,"[16, 10765, 18, 10759, 35]",8.7,1300,11,14,18,80,0,0,series
12,246,Avatar: The Last Airbender,2005-02-21,"[16, 10759, 10765, 0, 0]",8.7,3280,12,53,80,0,0,0,series
13,31132,Regular Show,2010-09-06,"[16, 35, 0, 0, 0]",8.7,1688,13,37,0,0,0,0,series
14,114410,Chainsaw Man,2022-10-12,"[16, 10759, 10765, 35, 0]",8.7,1049,14,35,18,10749,0,0,series
15,83121,Kaguya-sama: Love Is War,2019-01-12,"[16, 35, 18, 0, 0]",8.7,612,15,10749,16,0,0,0,series
16,135157,Alchemy of Souls,2022-06-18,"[18, 10759, 9648, 10765, 0]",8.7,349,16,12,14,28,0,0,series
17,89456,Primal,2019-10-08,"[10759, 16, 18, 0, 0]",8.7,1182,17,18,80,0,0,0,series
18,46298,Hunter x Hunter,2011-10-02,"[10759, 16, 18, 0, 0]",8.7,1374,18,28,12,16,18,0,series
19,213762,Be Eternal: Champions of America,2022-11-03,"[99, 0, 0, 0, 0]",8.7,111,19,16,10751,12,14,0,series

In [ ]:
####################################################################################################

In [224]:
## uno los dataframe ##
df_streaming=pd.concat([peliculas,series_tv], ignore_index=True)

#print(df_streaming)

In [137]:
###insert  un DF de generos
url='https://api.themoviedb.org/3/genre/movie/list?api_key=76f3ff736cde9a95c8dde41456f28cda&language=en-US'
response = requests.get(url)
if response.status_code==200:
      
            generos = pd.DataFrame(response.json()["genres"])[['id','name']]
        
        
for i in range(1, 4):
             response = requests.get(url)
             temp_df = pd.DataFrame(response.json()["genres"])[['id','name']]
             generos.append(temp_df, ignore_index=False)
        
        
             #print(generos) ##Visualizo los datos

C:\Users\Adriana Prieto\AppData\Local\Temp\ipykernel_47536\2710919535.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  generos.append(temp_df, ignore_index=False)
C:\Users\Adriana Prieto\AppData\Local\Temp\ipykernel_47536\2710919535.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  generos.append(temp_df, ignore_index=False)
C:\Users\Adriana Prieto\AppData\Local\Temp\ipykernel_47536\2710919535.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  generos.append(temp_df, ignore_index=False)

In [201]:
## Modifico ID y nombre de DF generos para cruzarlo con cada id generos de DF df_streaming
G0=generos.copy()
G0.rename(columns = {'id':'G0','name':'name0'}, inplace = True)

G1=generos.copy()
G1.rename(columns = {'id':'G1','name':'name1'}, inplace = True)

G2=generos.copy()
G2.rename(columns = {'id':'G2','name':'name2'}, inplace = True)

G3=generos.copy()
G3.rename(columns = {'id':'G3','name':'name3'}, inplace = True)

G4=generos.copy()
G4.rename(columns = {'id':'G4','name':'name4'}, inplace = True)

In [202]:
###Cruzo df  df_streaming con el DF detalle de generos
df_streaming=pd.merge(df_streaming,G0,on='G0',how='left')
df_streaming=pd.merge(df_streaming,G1,on='G1',how='left')
df_streaming=pd.merge(df_streaming,G2,on='G2',how='left')
df_streaming=pd.merge(df_streaming,G3,on='G3',how='left')
df_streaming=pd.merge(df_streaming,G4,on='G4',how='left')
#df_streaming

In [203]:
## Reemplazo los nulls con espacios
df_streaming['name1'].fillna("", inplace = True)
df_streaming['name2'].fillna("", inplace = True)
df_streaming['name3'].fillna("", inplace = True)
df_streaming['name4'].fillna("", inplace = True)

In [217]:
 #concateno los diferentes campos que tieen un genero
df_streaming['genero'] =pd.DataFrame( np.where(df_streaming['name1']=='' ,df_streaming.name0, df_streaming.name0.str.cat(df_streaming.name1, sep=', ')))
df_streaming['genero'] =pd.DataFrame( np.where(df_streaming['name2']=='' ,df_streaming.genero, df_streaming.genero.str.cat(df_streaming.name2, sep=', ')))
df_streaming['genero'] =pd.DataFrame( np.where(df_streaming['name3']=='' ,df_streaming.genero, df_streaming.genero.str.cat(df_streaming.name3, sep=', ')))
df_streaming['genero'] =pd.DataFrame( np.where(df_streaming['name4']=='' ,df_streaming.genero, df_streaming.genero.str.cat(df_streaming.name4, sep=', ')))
                       
#df_streaming

In [219]:
## Tomo solo las columnas que me interesa llevar ##
df_streaming=df_streaming.loc[:, ['id','tipo_streaming','nombre','fecha_lanzamiento','genero','voto_prom','voto_cant' ]]

df_streaming

,id,tipo_streaming,nombre,fecha_lanzamiento,genero,voto_prom,voto_cant
0,238,peliculas,The Godfather,1972-03-14,"Drama, Crime",8.7,17944
1,278,peliculas,The Shawshank Redemption,1994-09-23,"Drama, Crime",8.7,23783
2,772071,peliculas,Cuando Sea Joven,2022-09-14,"Comedy, Fantasy",8.6,226
3,240,peliculas,The Godfather Part II,1974-12-20,"Drama, Crime",8.6,10831
4,19404,peliculas,दिलवाले दुल्हनिया ले जायेंगे,1995-10-19,"Comedy, Drama, Romance",8.6,4131
5,424,peliculas,Schindler's List,1993-12-15,"Drama, History, War",8.6,14068
6,129,peliculas,千と千尋の神隠し,2001-07-20,"Animation, Family, Fantasy",8.5,14302
7,389,peliculas,12 Angry Men,1957-04-10,Drama,8.5,7273
8,372058,peliculas,君の名は。,2016-08-26,"Romance, Animation, Drama",8.5,9840
9,496243,peliculas,기생충,2019-05-30,"Comedy, Thriller, Drama",8.5,15734
10,155,peliculas,The Dark Knight,2008-07-14,"Drama, Action, Crime, Thriller",8.5,29719
11,497,peliculas,The Green Mile,1999-12-10,"Fantasy, Drama, Crime",8.5,15406
12,680,peliculas,Pulp Fiction,1994-09-10,"Thriller, Crime",8.5,25179
13,429,peliculas,"Il buono, il brutto, il cattivo",1966-12-23,Western,8.5,7396
14,13,peliculas,Forrest Gump,1994-06-23,"Comedy, Drama, Romance",8.5,24664
15,372754,peliculas,同級生,2016-02-20,"Romance, Animation",8.5,304
16,122,peliculas,The Lord of the Rings: The Return of the King,2003-12-01,"Adventure, Fantasy, Action",8.5,21594
17,769,peliculas,GoodFellas,1990-09-12,"Drama, Crime",8.5,11256
18,704264,peliculas,Primal: Tales of Savagery,2019-11-21,"Action, Adventure, Animation, Drama",8.5,263
19,995133,peliculas,"The Boy, the Mole, the Fox and the Horse",2022-12-25,"Animation, Family, Adventure, Fantasy",8.5,323
20,1396,series,Breaking Bad,2008-01-20,"Drama, Crime",8.9,11690
21,94605,series,Arcane,2021-11-06,"Drama, Crime",8.8,3061
22,100088,series,The Last of Us,2023-01-15,"Comedy, Fantasy",8.7,3485
23,60625,series,Rick and Morty,2013-12-02,"Drama, Crime",8.7,8204
24,37854,series,One Piece,1999-10-20,"Comedy, Drama, Romance",8.7,3733
25,31911,series,Fullmetal Alchemist: Brotherhood,2009-04-05,"Drama, History, War",8.7,1630
26,70785,series,Anne with an E,2017-03-19,"Animation, Family, Fantasy",8.7,4254
27,85937,series,Demon Slayer: Kimetsu no Yaiba,2019-04-06,Drama,8.7,5199
28,67915,series,Goblin,2016-12-02,"Romance, Animation, Drama",8.7,2469
29,65930,series,My Hero Academia,2016-04-03,"Comedy, Thriller, Drama",8.7,4327
30,95557,series,Invincible,2021-03-25,"Drama, Action, Crime, Thriller",8.7,3480
31,92685,series,The Owl House,2020-01-10,"Fantasy, Drama, Crime",8.7,1300
32,246,series,Avatar: The Last Airbender,2005-02-21,"Thriller, Crime",8.7,3280
33,31132,series,Regular Show,2010-09-06,Western,8.7,1688
34,114410,series,Chainsaw Man,2022-10-12,"Comedy, Drama, Romance",8.7,1049
35,83121,series,Kaguya-sama: Love Is War,2019-01-12,"Romance, Animation",8.7,612
36,135157,series,Alchemy of Souls,2022-06-18,"Adventure, Fantasy, Action",8.7,349
37,89456,series,Primal,2019-10-08,"Drama, Crime",8.7,1182
38,46298,series,Hunter x Hunter,2011-10-02,"Action, Adventure, Animation, Drama",8.7,1374
39,213762,series,Be Eternal: Champions of America,2022-11-03,"Animation, Family, Adventure, Fantasy",8.7,111

In [220]:
###Conexion Redshift###
url="data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws"
data_base="data-engineer-database"
user="marce200452_coderhouse"
#with open("C:/Users/Windows/Downloads/pwd_coder.txt",'r') as f:
pwd="2NA8hfK5c3" #f.read()

try:
    conn = psycopg2.connect(
        host='data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com',
        dbname=data_base,
        user=user,
        password=pwd,
        port='5439'
    )
    print("Connected to Redshift successfully!")
    
except Exception as e:
    print("Unable to connect to Redshift.")
    print(e)

Connected to Redshift successfully!

In [221]:
df_streaming.dtypes

id                     int64
tipo_streaming        object
nombre                object
fecha_lanzamiento     object
genero                object
voto_prom            float64
voto_cant              int64
dtype: object

In [222]:
###Insertar Datos##
def cargar_en_redshift(conn, table_name, dataframe):
    dtypes= df_streaming.dtypes
    df_streaming.dtypes
    cols= list(dtypes.index )
    tipos= list(dtypes.values)
    type_map = {'int64': 'INT','object': 'VARCHAR(500)','object': 'VARCHAR(100)','object': 'VARCHAR(100)','object': 'VARCHAR(100)','float64': 'Decimal(10,2)','int64': 'INT'}
    sql_dtypes = [type_map[str(dtype)] for dtype in tipos]
       
       # Combine column definitions into the CREATE TABLE statement
    column_defs = [f"{name} {data_type}" for name, data_type in zip(cols, sql_dtypes)]
    table_schema = f"""
             CREATE TABLE IF NOT EXISTS {table_name} (
                 {', '.join(column_defs)}
            );
            """
        #print(table_schema)
#Crear la tabla
    cur = conn.cursor()
    cur.execute(table_schema)
#     # Generar los valores a insertar
    values = [tuple(x) for x in df_streaming.to_numpy()]
# Definir el INSERT
    insert_sql = f"INSERT INTO {table_name} ({', '.join(cols)}) VALUES %s"
        
      
     # Execute the transaction to insert the data
    cur.execute("BEGIN")
    execute_values(cur, insert_sql, values)
    cur.execute("COMMIT")
    print('Proceso terminado')

In [223]:
    
    ## Llama funcion cargar datos ##
    cargar_en_redshift(conn=conn, table_name='streaming_videos', dataframe=df_streaming)

Proceso terminado